# 'test' mode is also used for prediction (inference)
AVAILABLE_MODES = ('fully-supervised', 'weakly-supervised', 'val', 'test')
SDR = 32  # SMALLEST DOWNSAMPLING RATIO
TRAIN_IMAGE_SIZE = (512, 640)
# TRAIN_IMAGE_SIZE = 1024
TEST_IMAGE_SIZE = (512, 640)
BATCH_SIZE = 4
ISOTROPIC_GAUSSIAN_MAP_SIZE = 512
REGION_THRESHOLD = 0.65 * 255
AFFINITY_THRESHOLD = 0.65 * 255
NEG_POS_RATIO = 3
DATA_LOADING_NUM_WORKERS = 6
